version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - esm_af_network

  core-api:
    container_name: core-api-container
    build:
      context: core-api
      dockerfile: Dockerfile
    env_file:
      - dev.env
    depends_on:
      - rabbitmq
    expose:
      - 8000
    volumes:
      - /Users/gvyarduhin/Siemens/MicroVM/data/uniprot:/opt/openfold/uniprot
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - esm_af_network

  esm-worker:
    container_name: esm-worker-container
    build:
      context: esm-worker
      dockerfile: Dockerfile
    env_file:
      - dev.env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - esm_af_network

networks:
  esm_af_network:
    driver: bridge
