version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - esm_af_network

  core-api:
    container_name: core-api-container
    build:
      context: core-api
      dockerfile: Dockerfile
    env_file:
      - dev.env
    depends_on:
      - rabbitmq
    expose:
      - 8000
    volumes:
      - /mnt/alphafold/input/esm/app/uniprot:/opt/openfold/uniprot
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - esm_af_network

  esm-worker:
    container_name: esm-worker-container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    build:
      context: esm-worker
      dockerfile: Dockerfile
    env_file:
      - dev.env
    depends_on:
      - rabbitmq
    volumes:
      - /mnt/alphafold/input/esm/app/uniprot:/opt/openfold/uniprot
      - /mnt/alphafold/input/esm/app/esm:/opt/openfold/esm
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - esm_af_network

networks:
  esm_af_network:
    driver: bridge
