version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - esm_af_network

  core-api:
    container_name: core-api-container
    build:
      context: core-api
      dockerfile: Dockerfile
    env_file:
      - dev.env
    depends_on:
      - rabbitmq
    expose:
      - 8000
    volumes:
      - /mnt/alphafold/input/esm/app/uniprot:/opt/openfold/uniprot
      - /mnt/alphafold/input/esm/app/pdb:/opt/openfold/pdb
      - /mnt/alphafold/input/esm/app/af:/opt/openfold/af
      - /mnt/alphafold/input/esm/app/esm:/opt/openfold/esm
      - /mnt/alphafold/input/esm/app/results:/opt/openfold/results
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - esm_af_network


#  esm-worker:
#    container_name: esm-worker-container
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
#    build:
#      context: esm-worker
#      dockerfile: Dockerfile
#    env_file:
#      - dev.env
#    depends_on:
#      - rabbitmq
#    volumes:
#      - /mnt/alphafold/input/esm/app/uniprot:/opt/openfold/uniprot
#      - /mnt/alphafold/input/esm/app/esm:/opt/openfold/esm
#      - /mnt/alphafold/input/esm/checkpoints:/root/.cache/torch/hub/checkpoints
#    environment:
#      - RABBITMQ_HOST=rabbitmq
#    networks:
#      - esm_af_network

  af-worker:
    container_name: af-worker-container
    build:
      context: af-worker
      dockerfile: Dockerfile
    env_file:
      - dev.env
    depends_on:
      - rabbitmq
    volumes:
      - /mnt/alphafold/input/esm/app/uniprot:/opt/openfold/uniprot
      - /mnt/alphafold/input/esm/app/pdb:/opt/openfold/pdb
      - /mnt/alphafold/input/esm/app/af:/opt/openfold/af
      - /mnt/alphafold/input/esm/app/esm:/opt/openfold/esm
      - /mnt/alphafold/input/esm/app/results:/opt/openfold/results
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - esm_af_network


  foldseek-worker:
    container_name: foldseek-worker-container
    build:
      context: foldseek-worker
      dockerfile: Dockerfile
    env_file:
      - dev.env
    depends_on:
      - rabbitmq
    volumes:
      - /mnt/alphafold/input/esm/app/uniprot:/opt/openfold/uniprot
      - /mnt/alphafold/input/esm/app/pdb:/opt/openfold/pdb
      - /mnt/alphafold/input/esm/app/af:/opt/openfold/af
      - /mnt/alphafold/input/esm/app/esm:/opt/openfold/esm
      - /mnt/alphafold/input/esm/app/results:/opt/openfold/results
      - /home/ubuntu/foldseek:/opt/foldseek
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - esm_af_network

networks:
  esm_af_network:
    driver: bridge
